package com.holmal.app.holmal.utils;

import android.content.Context;
import android.content.Intent;
import android.support.annotation.NonNull;
import android.support.v7.widget.CardView;
import android.support.v7.widget.RecyclerView;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import com.holmal.app.holmal.R;
import com.holmal.app.holmal.ShoppingListActivity;
import com.holmal.app.holmal.model.ShoppingList;
import java.util.HashMap;


/**
 * This adapter is responsible for displaying the lists of a household in an overview.
 * Is called in AllShoppingListsActivity.
 */
public class ShoppingListsAdapter extends RecyclerView.Adapter<ShoppingListsAdapter.ListsViewHolder>{

    private Context context;
    private HashMap<String, ShoppingList> shoppinglists;
    private String[] listKeys;

    private TextView nameView;
    private TextView categoryView;
    private TextView descriptionView;

    /**
     * Provide a reference to the views for each data item
     */
    public static class ListsViewHolder extends RecyclerView.ViewHolder {
        private View gridView;
        private ListsViewHolder(View view) {
            super(view);
            gridView = view;
        }
    }

    /**
     * Constructor of the adapter
     * @param context the context of AllShoppingLists the adapter needs
     * @param shoppinglists a list of all shopping lists a household has
     */
    public ShoppingListsAdapter(Context context, HashMap<String, ShoppingList> shoppinglists) {
        this.context = context;
        this.shoppinglists = shoppinglists;
        listKeys = shoppinglists.keySet().toArray(new String[shoppinglists.size()]);
    }

    /**
     * Method that creates views for the lists. Their layout is specified in single_shoppinglist_layout.
     * @param parent viewgroup the views for the lists lay on
     * @param i type of view
     * @return the list view holder
     */
    @NonNull
    @Override
    public ShoppingListsAdapter.ListsViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int i) {

        LayoutInflater inflater = (LayoutInflater) context
                .getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        View gridView = inflater.inflate(R.layout.single_shoppinglist_layout, parent, false);

        nameView = (TextView) gridView.findViewById(R.id.nameOfList);
        categoryView = (TextView) gridView.findViewById(R.id.categoryOfList);
        descriptionView = (TextView) gridView.findViewById(R.id.amountItemsOnList);

        ListsViewHolder viewHolder = new ListsViewHolder(gridView);
        return viewHolder;
    }


    @Override
    public void onBindViewHolder(@NonNull ShoppingListsAdapter.ListsViewHolder listsViewHolder, int i) {

        ShoppingList listAtPosition = shoppinglists.get(listKeys[i]);

        nameView.setText(listAtPosition.getListName());

        categoryView.setText(listAtPosition.getCategory());

        if (listAtPosition.getItemsOfThisList() == null
                || listAtPosition.getItemsOfThisList().size() == 0) {
            descriptionView.setText(R.string.noOpenItems);
        } else {
            descriptionView.setText(R.string.openItems);
            descriptionView.append(String.valueOf(listAtPosition.getItemsOfThisList().size()));
        }

        //handles click on list to see it in a shopping list view
        listsViewHolder.gridView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Log.i("FürSvenja", "clicked list -> open list");
                Intent intent = new Intent(context, ShoppingListActivity.class);
                v.getContext().startActivity(intent);
            }
        });

    }

    //only autogenerated
    @Override
    public long getItemId(int position) {
        return 0;
    }

    @Override
    public int getItemCount() {
        return shoppinglists.size();
    }


}
