package com.holmal.app.holmal.utils;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import android.widget.TextView;
import com.holmal.app.holmal.R;


//this class is responsible for displaying the lists in the list overview
public class ShoppingListsAdapter extends BaseAdapter {

    private Context context;
    private FireBaseHandling fireBaseHandling = FireBaseHandling.getInstance();
    private ShoppingListListener listener = fireBaseHandling.getShoppingListListener();
    private String openItems = " offene Items";

    //constructor
    public ShoppingListsAdapter(Context context){
        this.context = context;
    }

    @Override
    public int getCount() {
        return listener.getShoppingListList().size();
    }

    @Override
    public Object getItem(int position) {
        return listener.getShoppingListList().get(position);
    }

    //only autogenerated
    @Override
    public long getItemId(int position) {
        return 0;
    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {

        LayoutInflater inflater = (LayoutInflater) context
                .getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        convertView = inflater.inflate(R.layout.single_shoppinglist_layout, parent, false);


        /*
          Bundle extras =  intent.getExtras();
        String householdId = extras.getString("inputId");
        // listener fuer personen starten, gleich bei erzeugen, bevor Person gespeichert, wegen Abfragen ob bereits in Haushalt vorhanden
        fireBaseHandling.startPersonValueEventListener(householdId);
         */


        TextView nameView = (TextView) convertView.findViewById(R.id.nameOfList);
        TextView descriptionView = (TextView) convertView.findViewById(R.id.amountItemsOnList);

        for(int i = 0; i< listener.getShoppingListList().size(); i++){

            nameView.setText(listener.getShoppingListList().get(i).getListName());

            descriptionView.setText(listener.getShoppingListList().get(i).getItemsOfThisList().length);
            descriptionView.append(openItems);

        }

        return convertView;
    }
}
