package com.holmal.app.holmal.utils;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import android.widget.TextView;
import com.holmal.app.holmal.R;
import com.holmal.app.holmal.model.ShoppingList;

import java.util.List;


//this class is responsible for displaying the lists in the list overview
public class ShoppingListsAdapter extends BaseAdapter {

    private Context context;
    private List<ShoppingList> shoppinglists;
    private String openItems = " offene Items";

    //constructor
    public ShoppingListsAdapter(Context context, List<ShoppingList> shoppinglists){
        this.context = context;
        this.shoppinglists = shoppinglists;
    }

    @Override
    public int getCount() {
        return shoppinglists.size();
    }

    @Override
    public Object getItem(int position) {
        return shoppinglists.get(position);
    }

    //only autogenerated
    @Override
    public long getItemId(int position) {
        return 0;
    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {

        LayoutInflater inflater = (LayoutInflater) context
                .getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        convertView = inflater.inflate(R.layout.single_shoppinglist_layout, parent, false);

        TextView nameView = (TextView) convertView.findViewById(R.id.nameOfList);
        TextView descriptionView = (TextView) convertView.findViewById(R.id.amountItemsOnList);

        for(int i = 0; i< shoppinglists.size(); i++){

            nameView.setText(shoppinglists.get(i).getListName());

            if(shoppinglists.get(i).getItemsOfThisList()==null || shoppinglists.get(i).getItemsOfThisList().size() == 0){
                descriptionView.setText("Keine");
                descriptionView.append(openItems);
            }
            else {
                descriptionView.setText(shoppinglists.get(i).getItemsOfThisList().size());
                descriptionView.append(openItems);
            }
        }

        return convertView;
    }
}
